spring.datasource.url=jdbc:tc:mysql:8.4:///financehub_test
spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver
spring.datasource.username=test
spring.datasource.password=test

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration,classpath:db/test-migration